trigger:
- master

pool:
  name: 'default'

variables:
  GOBIN:  '$(system.defaultWorkingDirectory)/bin'

steps:
- script: |
    mkdir -p '$(GOBIN)'
    echo '##vso[task.prependpath]$(GOBIN)'
  displayName: '[PIPELINE] Set up Go environment'

- script: |
    go version
    if [ ! -f go.mod ]; then
        go mod init richmondpapersupply.co.uk # replace with your module path
    fi
    go mod tidy
    go mod download
    if [ -f Gopkg.toml ]; then
        curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        dep ensure
    fi
    go build -v .
  workingDirectory: '$(system.defaultWorkingDirectory)'
  displayName: '[PIPELINE] Run build'
