version: '3.8'
services:
  richmond-paper-supply-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5080:5080"
    restart: unless-stopped
    environment:
      PORT: 5080
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
